server:
  port: 8081
  address: localhost

spring:
  application:
    name: films-titles-and-id-service
  boot:
    admin:
      client:
        url:
        - "http://localhost:8761/admin"
  datasource:
    url: jdbc:mysql://localhost/films-titles
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: dd-MM-yyyy

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url: ["http://localhost:8761/eureka/"]

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS