server:
  port: 8081

spring:
  application:
    name: films-titles-and-id-service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url: ["http://localhost:8761/eureka/"]