server:
  port: 8080
  address: 127.0.0.1

spring:
  application:
    name: service-aggregator
  boot:
    admin:
      client:
        url:
        - "http://localhost:8079/admin"

eureka:
  instance:
    health-check-url: ${server.address}:${server.port}/actuator/health
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}
  client:
    service-url: ["http://localhost:8761/eureka/"]

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: service_aggregator.log