server:
  port: 8080

spring:
  application:
    name: films-aggregator-service
  boot:
    admin:
      client:
        url:
          - "http://localhost:8761/admin"

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url: ["http://localhost:8761/eureka/"]

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS