server:
  port: 8761
  address: 127.0.0.1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
  instance:
    health-check-url: ${server.address}:${server.port}/actuator/health
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

spring:
  application:
    name: eureka-service-registry
  boot:
    admin:
      client:
        url:
        - "http://localhost:8079/admin"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: eureka_service_registry.log