INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le Seigneur des Anneaux : la Communauté de l\'Anneau');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le Seigneur des Anneaux : les deux Tours');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le Seigneur des Anneaux : le retour du Roi');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Django Unchained');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Venom');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'A Star Is Born');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le Parrain');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'The Dark Knight: Le chevalier noir');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'La liste de Schindler');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Pulp Fiction');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Fight Club');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Forest Gump');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Inception');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Matrix');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Usual Suspects');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Léon');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'La ligne verte');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Interstellar');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Psychose');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Intouchables');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le pianiste');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Retour vers le futur');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Gladiator');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le Roi Lion');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le prestige');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Avengers: Infinity War');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Shining');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'The Dark Knight Rises');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Requiem for a Dream');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Orange mécanique');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le fabuleux destin d\'Amélie Poulain');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Toy Story');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Inglourious Basterds');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Shining');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Will Hunting');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Monty Python sacré graal!');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Scarface');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Indiana Jones et la dernière croisade');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Là-haut');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Batman Begins');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le labyrinthe de Pan');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Mon voisin Totoro');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le pont de la rivière Kwaï');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Un homme d\'exception');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le loup de Wall Street');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'V pour vendetta');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le monde de Nemo');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Kill Bill');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Jurassic Park');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Into the Wild');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Au nom du père');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'The Grand Budapest hotel');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'The Truman Show');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Ben-Hur');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, '12 Years a Slave');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Million Dollar Baby');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Mad Max: Fury Road');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Spotlight');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Logan');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Arrête-moi si tu peux');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Rocky');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Monstres et Cie');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le cercle des poètes disparus');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Blade Runner 2049');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'La La Land');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Les dents de la mer');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'La vengeance dans la peau');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Les gardiens de la galaxie');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Le château dans le ciel');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Pirates des Caraïbes - La malédiction du Black Pearl');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Aladdin');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Aquaman');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Bohemian Rhapsody');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Hellboy');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Ant-Man et la Guêpe');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, '	Les Animaux fantastiques');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Deadpool');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Deadpool 2');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Jurassic World');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Jurassic World: Fallen Kingdom');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'The Greatest Showman');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Captain Marvel');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Ocean\'s 8');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Mamma Mia! Here We Go Again');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Black Panther');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Ready Player One');
INSERT INTO `film` (`id`, `title`) VALUES (NULL, 'Harry Potter à l\'école des sorciers');